name: Test
on:
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@main
        with:
          core: true
          cask: false
      - run: brew install zizmor
      - run: gh api rate_limit
      - run: cd $(brew --repo homebrew/core) && zizmor . -vv || true
      - run: gh api rate_limit
